Update patch set 2
Patch Set 2:

Do you expect "go test" to succeed? Because it fails on my windows/386 with:

=== RUN   TestOpen
--- FAIL: TestOpen (0.02s)
        mmap_test.go:18: Open: open mmap_test.go: The system cannot find the file specified.
FAIL

Alex

Patch-set: 2