Update patch set 1
Patch Set 1:

Still fails.

It looks like the problematic import still comes in via gldriver.go, screen.go, texture.go, and window.go.

(The problem is not just the direct use of cgo, but also the use of the package golang.org/x/mobile/gl — which itself fails to build when cgo is disabled.)



~/src/golang.org/x/exp$ git log -n 1
commit 992e46932e70a78a22b6508d15e206d1aee875ce (HEAD)
Author: Nigel Tao <nigeltao@golang.org>
Date:   Wed Jul 3 17:01:22 2019 +1000

    shiny/driver/gldriver: add cgo build tag

    Fixes golang/go#32837

    Change-Id: I5432d952b57e46460bac1598619e90a18f29e5e0

~/src/golang.org/x/exp$ CGO_ENABLED=1 go build ./...

~/src/golang.org/x/exp$ CGO_ENABLED=0 go build ./...
# golang.org/x/mobile/gl
../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20190312151609-d3739f865fa6/gl/gl.go:20:12: undefined: context
../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20190312151609-d3739f865fa6/gl/gl.go:29:12: undefined: context
../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20190312151609-d3739f865fa6/gl/gl.go:39:12: undefined: context
../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20190312151609-d3739f865fa6/gl/gl.go:53:12: undefined: context
../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20190312151609-d3739f865fa6/gl/gl.go:63:12: undefined: context
../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20190312151609-d3739f865fa6/gl/gl.go:73:12: undefined: context
../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20190312151609-d3739f865fa6/gl/gl.go:83:12: undefined: context
../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20190312151609-d3739f865fa6/gl/gl.go:93:12: undefined: context
../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20190312151609-d3739f865fa6/gl/gl.go:102:12: undefined: context
../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20190312151609-d3739f865fa6/gl/gl.go:114:12: undefined: context
../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20190312151609-d3739f865fa6/gl/gl.go:114:12: too many errors

Patch-set: 1
Reviewer: Gerrit User 6365 <6365@62eb7196-b449-3ce5-99f1-c037f21e1705>